name: scratch_vit
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python == 3.10
  - pytorch
  - torchvision
  - cupy
  - pillow
  - matplotlib
  - numpy=1.*
  - ipykernel
  - unittest
  - scipy
  - pip
  - pip:
      - opencv-python
      - timm
      - wandb
