name: scratch_vit
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python == 3.10
  - pytorch
  - cupy
  - pillow
  - matplotlib
  - numpy=1.*
  - pip
  - pip:
    - opencv-python
    - timm
    - wandb